services:
  react:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: react
    ports:
      - "3000:80"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx   
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - react
    networks:
      - app-network

networks:
  app-network:
    external: true