services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile        
    image: ptsd-app
    container_name: ptsd-app
    ports:
      - "8081:8000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENV=production
    restart: always
    networks:
      - app-network

  mosquitto:  
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/ubuntu/S12P31D101/backend/PTSD/core/mosquitto/mosquitto.conf:/mosquitto/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    command: mosquitto -c /mosquitto/mosquitto.conf
    restart: always
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  jenkins-data:
  mosquitto-data:
  mosquitto-log:
#ss