services:
  app:
    build:
      context: ../backend   
      dockerfile: Dockerfile
    image: ptsd-app
    container_name: ptsd-app
    ports:
      - "8081:8081"
    restart: always
    networks:
      - app-network
    env_file:
      - ../backend/.env

networks:
  app-network:
    external: true


#제발 되라
