services:
  backend:
    build:
      context: ../../backend/ptsd  
      dockerfile: Dockerfile        
    image: ptsd-app
    container_name: ptsd-app
    ports:
      - "8081:8081"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - app-network

networks:
  app-network:
    external: true
