version: '3'

services:
  backend:
    build:
      context: ../../backend/ptsd  
      dockerfile: Dockerfile        
    image: ptsd-app
    container_name: ptsd-app
    ports:
      - "8081:8081"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    external: true
