"""initial migration

Revision ID: a5cb3df46a74
Revises: 
Create Date: 2025-04-25 09:58:32.576601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5cb3df46a74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_routines_routineId', table_name='routines')
    op.drop_table('routines')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_userId', table_name='users')
    op.drop_table('users')
    op.drop_table('devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], name='devices_user_id_fkey'),
    sa.PrimaryKeyConstraint('device_id', name='devices_pkey')
    )
    op.create_table('users',
    sa.Column('userId', sa.INTEGER(), server_default=sa.text('nextval(\'"users_userId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('userId', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_userId', 'users', ['userId'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('routines',
    sa.Column('routineId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('startTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('routineType', postgresql.ENUM('once', 'daily', name='routine_type_enum'), autoincrement=False, nullable=False),
    sa.Column('isWork', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('repeatDays', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name='routines_userId_fkey'),
    sa.PrimaryKeyConstraint('routineId', name='routines_pkey')
    )
    op.create_index('ix_routines_routineId', 'routines', ['routineId'], unique=False)
    # ### end Alembic commands ###
