"""add cascade options

Revision ID: ecda8b1a9370
Revises: a5cb3df46a74
Create Date: 2025-04-25 10:04:15.283660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecda8b1a9370'
down_revision: Union[str, None] = 'a5cb3df46a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_routines_routineId', table_name='routines')
    op.drop_table('routines')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routines',
    sa.Column('routineId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('startTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('routineType', postgresql.ENUM('once', 'daily', name='routine_type_enum'), autoincrement=False, nullable=False),
    sa.Column('isWork', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('repeatDays', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('routineId', name='routines_pkey')
    )
    op.create_index('ix_routines_routineId', 'routines', ['routineId'], unique=False)
    # ### end Alembic commands ###
